# Generated by Django 4.2.20 on 2025-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rental",
            "0002_alter_customuser_managers_remove_customuser_username_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="rental_book_user_id_358740_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="rental_book_vehicle_5a1764_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="rental_book_status_a2fbee_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="rental_book_payment_161a55_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="rental_book_created_ab9e4b_idx",
        ),
        migrations.AddField(
            model_name="booking",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CREDIT_CARD", "Credit Card"), ("DEBIT_CARD", "Debit Card")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(),
        ),
    ]
